title: "Nghia Dang's Resume"
email: dtnghia1987@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the professional resume of Nghia Dang, specializing in Data Science and Machine Learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tedtdang.github.io/resume" # the base hostname & protocol for your site

theme: minima

markdown: kramdown

# Custom CSS
sass:
  style: compressed

# Build settings
plugins:
  - jekyll-feed
